# Generated by Django 3.2.12 on 2023-02-04 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_delete_movieinteraction'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(blank=True, default=False)),
                ('watched', models.BooleanField(blank=True, default=False)),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='movies_interaction',
            field=models.ManyToManyField(through='profiles.MovieInteraction', to='movies.Movie'),
        ),
    ]
