# Generated by Django 3.2.12 on 2023-02-04 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
