# Generated by Django 3.2.12 on 2023-02-04 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('folders', '0004_remove_folder_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='profiles.profile'),
        ),
    ]
