# Generated by Django 3.2.12 on 2023-02-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230203_2009'),
        ('folders', '0005_folder_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='movies',
            field=models.ManyToManyField(null=True, related_name='folders', to='movies.Movie'),
        ),
    ]
