# Generated by Django 3.2.12 on 2023-02-04 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230203_2009'),
        ('folders', '0008_auto_20230204_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='movies',
        ),
        migrations.AddField(
            model_name='folder',
            name='movies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='movies.movie'),
        ),
    ]
