# Generated by Django 3.2.12 on 2023-02-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_poster'),
        ('folders', '0009_auto_20230204_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='movies',
        ),
        migrations.AddField(
            model_name='folder',
            name='movies',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
