# Generated by Django 3.2.12 on 2023-02-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_poster'),
        ('folders', '0011_auto_20230204_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='movies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='movies.movie'),
        ),
    ]
