# Generated by Django 3.2.12 on 2023-02-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_poster'),
        ('folders', '0013_auto_20230204_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Movie'),
        ),
    ]
