# Generated by Django 3.2.12 on 2023-02-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_poster'),
        ('folders', '0014_alter_folder_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.folder')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        # migrations.AlterField(
        #     model_name='folder',
        #     name='movies',
        #     field=models.ManyToManyField(blank=True, null=True, through='folders.FolderMovies', to='movies.Movie'),
        # ),
    ]
