# Generated by Django 3.2.12 on 2023-02-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0015_auto_20230204_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foldermovies',
            old_name='folder',
            new_name='fol',
        ),
    ]
