# Generated by Django 3.2.12 on 2023-02-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_poster'),
        ('folders', '0016_rename_folder_foldermovies_fol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Movie'),
        ),
        migrations.DeleteModel(
            name='FolderMovies',
        ),
    ]
