# Generated by Django 3.2.12 on 2023-02-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('poster', models.ImageField(default='undefiend_poster.jpg', upload_to='posters_images/')),
                ('length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('director_name', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('age_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('countries', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
