# Generated by Django 3.2.12 on 2023-02-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230203_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='undefiend_poster.jpg', upload_to='posters_images/'),
        ),
    ]
