# Generated by Django 3.2.12 on 2023-02-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='undefiend_poster.jpg', null=True, upload_to='posters_images/'),
        ),
    ]
