# Generated by Django 3.2.12 on 2023-02-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='undefiend_poster.jpg', upload_to='posters_images/'),
        ),
    ]
