# Generated by Django 3.2.12 on 2023-02-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movieinteraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieInteraction',
        ),
    ]
